eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3
spring:
  application:
    name: service-cosume
server:
  port: 8089


feign:
  hystrix:
    enabled: true

